# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_anvilcode.ipynb.

# %% auto 0
__all__ = ['key', 'get_now_date2']

# %% ../nbs/01_anvilcode.ipynb 4
import datetime
import anvil.server
import os

# %% ../nbs/01_anvilcode.ipynb 5
key = os.environ.get('ANVIL_KEY')

if key is None:
    with open('anvil_license.txt') as file:
        key = file.read()

anvil.server.connect(key)

# %% ../nbs/01_anvilcode.ipynb 6
@anvil.server.callable
def get_now_date2():
  return "Ananth says  UTC time is " + str(datetime.datetime.today())
