# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_mtables.ipynb.

# %% auto 0
__all__ = ['table']

# %% ../nbs/00_mtables.ipynb 4
def table(n: int, # a number for which you want multiplication tables
         ):
    for i in range(1,11,1):
        print(f"{n} times {i} = {n*i}")
