# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_mtables.ipynb.

# %% auto 0
__all__ = ['table']

# %% ../nbs/00_mtables.ipynb 3
def table(n):
    for i in range(1,11,1):
        print(f"{n} times {n} = {n*i}")
